int ClearCommError(void)				{return 0;}
int CloseHandle(void)					{return 0;}
int CloseServiceHandle(void)			{return 0;}
int CreateFile(void)					{return 0;}
int CreateService(void)					{return 0;}
int DeleteService(void)					{return 0;}
int EscapeCommFunction(void)			{return 0;}
int FlushFileBuffers(void)				{return 0;}
int GetCommModemStatus(void)			{return 0;}
int GetLastError(void)					{return 0;}
int GetModuleFileName(void)				{return 0;}
int GetVersionEx(void)					{return 0;}
int OpenSCManager(void)					{return 0;}
int OpenService(void)					{return 0;}
int QueryPerformanceCounter(void)		{return 0;}
int QueryPerformanceFrequency(void)		{return 0;}
int ReadFile(void)						{return 0;}
int SearchPath(void)					{return 0;}
int SetCommState(void)					{return 0;}
int SetCommTimeouts(void)				{return 0;}
int StartService(void)					{return 0;}
int WriteFile(void)						{return 0;}
int _inp(void)							{return 0;}
int _outp(void)							{return 0;}
int hidasp_cmd(void)					{return 0;}
int hidasp_page_write(void)				{return 0;}
int hidasp_program_enable(void)			{return 0;}
int strnicmp(void)						{return 0;}
int usb_get_version(void)				{return 0;}
